In [58]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 500)

In [59]:
df = pd.read_excel("Telco_customer_churn_adapted_v2.xlsx")
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR)
0,0,2,Jakarta,Mid End,Yes,Yes,No,No,No,No,Digital Wallet,70.005,Yes,106.816666,-6.2,4210.7
1,1,2,Jakarta,High End,No,No,No,No,No,No,Pulsa,91.910,Yes,106.816666,-6.2,3511.3
2,2,8,Jakarta,High End,No,No,Yes,No,Yes,Yes,Pulsa,129.545,Yes,106.816666,-6.2,6983.6
3,3,28,Jakarta,High End,No,No,Yes,Yes,Yes,Yes,Pulsa,136.240,Yes,106.816666,-6.2,6503.9
4,4,49,Jakarta,High End,No,Yes,Yes,No,Yes,Yes,Debit,134.810,Yes,106.816666,-6.2,6942.0

In [60]:
df["Games Product"].value_counts()

No                     3498
Yes                    2019
No internet service    1526
Name: Games Product, dtype: int64

In [61]:
# le = LabelEncoder()

# for i in df.columns:
#     if df[i].dtype == 'object':
#         df[i] = le.fit_transform(df[i].astype(str))

# df.head()

In [62]:
df.columns

Index(['Customer ID', 'Tenure Months', 'Location', 'Device Class',
       'Games Product', 'Music Product', 'Education Product', 'Call Center',
       'Video Product', 'Use MyApp', 'Payment Method',
       'Monthly Purchase (Thou. IDR)', 'Churn Label', 'Longitude', 'Latitude',
       'CLTV (Predicted Thou. IDR)'],
      dtype='object')

In [63]:
# if no = 0, yes = 1, no internet service = 0

service = ['Games Product', 'Music Product', 'Education Product', 'Call Center', 'Video Product', 'Use MyApp']

for i in service:
    df[i] = df[i].replace(['No', 'Yes', 'No internet service'], [0, 1, 0])

df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR)
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,Yes,106.816666,-6.2,4210.7
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,Yes,106.816666,-6.2,3511.3
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,Yes,106.816666,-6.2,6983.6
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,Yes,106.816666,-6.2,6503.9
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,Yes,106.816666,-6.2,6942.0

In [64]:
df['service_used'] = df[service].sum(axis=1)

In [65]:
# make feature churn rate by payment method
df['Churn Label'] = df['Churn Label'].replace(['Yes', 'No'], [1, 0])
df.groupby('Payment Method')['Churn Label'].mean()

df['payment_method_churn_rate'] = df['Payment Method'].map(df.groupby('Payment Method')['Churn Label'].mean())
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098

In [66]:
# make feature churn rate by location
df.groupby('Location')['Churn Label'].mean()

df['location_churn_rate'] = df['Location'].map(df.groupby('Location')['Churn Label'].mean())
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297

In [67]:
# make feature churn rate by device owned
df.groupby('Device Class')['Churn Label'].mean()

df['device_churn_rate'] = df['Device Class'].map(df.groupby('Device Class')['Churn Label'].mean())
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928

In [68]:
df.groupby('Games Product')['Churn Label'].mean()

df['games_churn_rate'] = df['Games Product'].map(df.groupby('Games Product')['Churn Label'].mean())
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296

In [69]:
df.groupby('Music Product')['Churn Label'].mean()

df['music_churn_rate'] = df['Music Product'].map(df.groupby('Music Product')['Churn Label'].mean())
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315

In [70]:
df.groupby('Education Product')['Churn Label'].mean()

df['education_churn_rate'] = df['Education Product'].map(df.groupby('Education Product')['Churn Label'].mean())
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021

In [71]:
df.groupby('Call Center')['Churn Label'].mean()

df['call_center_churn_rate'] = df['Call Center'].map(df.groupby('Call Center')['Churn Label'].mean())
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862

In [72]:
df.groupby('Video Product')['Churn Label'].mean()

df['video_churn_rate'] = df['Video Product'].map(df.groupby('Video Product')['Churn Label'].mean())
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702

In [73]:
df.groupby('Use MyApp')['Churn Label'].mean()

df['myapp_churn_rate'] = df['Use MyApp'].map(df.groupby('Use MyApp')['Churn Label'].mean())
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414

In [74]:
df.groupby('service_used')['Churn Label'].mean()

df['service_used_churn_rate'] = df['service_used'].map(df.groupby('service_used')['Churn Label'].mean())
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005

In [75]:
# df.groupby(['Games Product', 'Music Product', 'Education Product', 'Video Product', 'Call Center', 'Use MyApp'])['Churn Label'].mean()

# df['service_churn_rate'] = df.groupby(['Games Product', 'Music Product', 'Education Product', 'Video Product', 'Call Center', 'Use MyApp'])['Churn Label'].transform('mean')

# df.head()

In [76]:
df.groupby(['Device Class', 'Games Product'])['Churn Label'].mean()

df['device_games_churn_rate'] = df.groupby(['Device Class', 'Games Product'])['Churn Label'].transform('mean')

df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate,device_games_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180,0.094915
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060,0.493576
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703,0.493576
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005,0.493576
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005,0.493576

In [77]:
df.groupby(['Device Class', 'Music Product'])['Churn Label'].mean()

df['device_music_churn_rate'] = df.groupby(['Device Class', 'Music Product'])['Churn Label'].transform('mean')
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate,device_games_churn_rate,device_music_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180,0.094915,0.106814
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060,0.493576,0.507701
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703,0.493576,0.507701
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005,0.493576,0.507701
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005,0.493576,0.303053

In [78]:
df.groupby(['Device Class', 'Education Product'])['Churn Label'].mean()

df['device_education_churn_rate'] = df.groupby(['Device Class', 'Education Product'])['Churn Label'].transform('mean')
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate,device_games_churn_rate,device_music_churn_rate,device_education_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180,0.094915,0.106814,0.252212
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060,0.493576,0.507701,0.499712
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703,0.493576,0.507701,0.315402
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005,0.493576,0.507701,0.315402
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005,0.493576,0.303053,0.315402

In [79]:
df.groupby(['Device Class', 'Call Center'])['Churn Label'].mean()

df['device_call_center_churn_rate'] = df.groupby(['Device Class', 'Call Center'])['Churn Label'].transform('mean')
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate,device_games_churn_rate,device_music_churn_rate,device_education_churn_rate,device_call_center_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180,0.094915,0.106814,0.252212,0.277554
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060,0.493576,0.507701,0.499712,0.493722
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703,0.493576,0.507701,0.315402,0.493722
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005,0.493576,0.507701,0.315402,0.226328
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005,0.493576,0.303053,0.315402,0.493722

In [80]:
df.groupby(['Device Class', 'Video Product'])['Churn Label'].mean()

df['device_video_churn_rate'] = df.groupby(['Device Class', 'Video Product'])['Churn Label'].transform('mean')
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate,device_games_churn_rate,device_music_churn_rate,device_education_churn_rate,device_call_center_churn_rate,device_video_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180,0.094915,0.106814,0.252212,0.277554,0.226776
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060,0.493576,0.507701,0.499712,0.493722,0.453195
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703,0.493576,0.507701,0.315402,0.493722,0.392571
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005,0.493576,0.507701,0.315402,0.226328,0.392571
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005,0.493576,0.303053,0.315402,0.493722,0.392571

In [81]:
df.groupby(['Device Class', 'Use MyApp'])['Churn Label'].mean()

df['device_myapp_churn_rate'] = df.groupby(['Device Class', 'Use MyApp'])['Churn Label'].transform('mean')
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate,device_games_churn_rate,device_music_churn_rate,device_education_churn_rate,device_call_center_churn_rate,device_video_churn_rate,device_myapp_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180,0.094915,0.106814,0.252212,0.277554,0.226776,0.223611
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060,0.493576,0.507701,0.499712,0.493722,0.453195,0.457993
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703,0.493576,0.507701,0.315402,0.493722,0.392571,0.388921
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005,0.493576,0.507701,0.315402,0.226328,0.392571,0.388921
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005,0.493576,0.303053,0.315402,0.493722,0.392571,0.388921

In [82]:
df.groupby(['Device Class', 'service_used'])['Churn Label'].mean()

df['device_service_churn_rate'] = df.groupby(['Device Class', 'service_used'])['Churn Label'].transform('mean')
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate,device_games_churn_rate,device_music_churn_rate,device_education_churn_rate,device_call_center_churn_rate,device_video_churn_rate,device_myapp_churn_rate,device_service_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180,0.094915,0.106814,0.252212,0.277554,0.226776,0.223611,0.202643
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060,0.493576,0.507701,0.499712,0.493722,0.453195,0.457993,0.604010
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703,0.493576,0.507701,0.315402,0.493722,0.392571,0.388921,0.379471
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005,0.493576,0.507701,0.315402,0.226328,0.392571,0.388921,0.318458
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005,0.493576,0.303053,0.315402,0.493722,0.392571,0.388921,0.318458

In [83]:
df.groupby(['Device Class', 'Location'])['Churn Label'].mean()

df['device_location_churn_rate'] = df.groupby(['Device Class', 'Location'])['Churn Label'].transform('mean')
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate,device_games_churn_rate,device_music_churn_rate,device_education_churn_rate,device_call_center_churn_rate,device_video_churn_rate,device_myapp_churn_rate,device_service_churn_rate,device_location_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180,0.094915,0.106814,0.252212,0.277554,0.226776,0.223611,0.202643,0.187318
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060,0.493576,0.507701,0.499712,0.493722,0.453195,0.457993,0.604010,0.410626
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703,0.493576,0.507701,0.315402,0.493722,0.392571,0.388921,0.379471,0.410626
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005,0.493576,0.507701,0.315402,0.226328,0.392571,0.388921,0.318458,0.410626
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005,0.493576,0.303053,0.315402,0.493722,0.392571,0.388921,0.318458,0.410626

In [84]:
df.groupby(['Device Class', 'Payment Method'])['Churn Label'].mean()

df['device_payment_method_churn_rate'] = df.groupby(['Device Class', 'Payment Method'])['Churn Label'].transform('mean')
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate,device_games_churn_rate,device_music_churn_rate,device_education_churn_rate,device_call_center_churn_rate,device_video_churn_rate,device_myapp_churn_rate,device_service_churn_rate,device_location_churn_rate,device_payment_method_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180,0.094915,0.106814,0.252212,0.277554,0.226776,0.223611,0.202643,0.187318,0.207178
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060,0.493576,0.507701,0.499712,0.493722,0.453195,0.457993,0.604010,0.410626,0.532288
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703,0.493576,0.507701,0.315402,0.493722,0.392571,0.388921,0.379471,0.410626,0.532288
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005,0.493576,0.507701,0.315402,0.226328,0.392571,0.388921,0.318458,0.410626,0.532288
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005,0.493576,0.303053,0.315402,0.493722,0.392571,0.388921,0.318458,0.410626,0.289474

In [85]:
df.groupby(['Location', 'Device Class', 'Payment Method'])['Churn Label'].mean()

df['location_device_payment_method_churn_rate'] = df.groupby(['Location', 'Device Class', 'Payment Method'])['Churn Label'].transform('mean')
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate,device_games_churn_rate,device_music_churn_rate,device_education_churn_rate,device_call_center_churn_rate,device_video_churn_rate,device_myapp_churn_rate,device_service_churn_rate,device_location_churn_rate,device_payment_method_churn_rate,location_device_payment_method_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180,0.094915,0.106814,0.252212,0.277554,0.226776,0.223611,0.202643,0.187318,0.207178,0.207675
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060,0.493576,0.507701,0.499712,0.493722,0.453195,0.457993,0.604010,0.410626,0.532288,0.529884
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703,0.493576,0.507701,0.315402,0.493722,0.392571,0.388921,0.379471,0.410626,0.532288,0.529884
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005,0.493576,0.507701,0.315402,0.226328,0.392571,0.388921,0.318458,0.410626,0.532288,0.529884
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005,0.493576,0.303053,0.315402,0.493722,0.392571,0.388921,0.318458,0.410626,0.289474,0.268657

In [86]:
df.groupby(['Location', 'Device Class', 'Payment Method', 'service_used'])['Churn Label'].mean()

df['location_device_payment_method_service_churn_rate'] = df.groupby(['Location', 'Device Class', 'Payment Method', 'service_used'])['Churn Label'].transform('mean')
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate,device_games_churn_rate,device_music_churn_rate,device_education_churn_rate,device_call_center_churn_rate,device_video_churn_rate,device_myapp_churn_rate,device_service_churn_rate,device_location_churn_rate,device_payment_method_churn_rate,location_device_payment_method_churn_rate,location_device_payment_method_service_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180,0.094915,0.106814,0.252212,0.277554,0.226776,0.223611,0.202643,0.187318,0.207178,0.207675,0.223404
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060,0.493576,0.507701,0.499712,0.493722,0.453195,0.457993,0.604010,0.410626,0.532288,0.529884,0.660920
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703,0.493576,0.507701,0.315402,0.493722,0.392571,0.388921,0.379471,0.410626,0.532288,0.529884,0.466135
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005,0.493576,0.507701,0.315402,0.226328,0.392571,0.388921,0.318458,0.410626,0.532288,0.529884,0.390071
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005,0.493576,0.303053,0.315402,0.493722,0.392571,0.388921,0.318458,0.410626,0.289474,0.268657,0.235294

In [87]:
df['location_device_payment_method_games_churn_rate'] = df.groupby(['Location', 'Device Class', 'Payment Method', 'Games Product'])['Churn Label'].transform('mean')
df['location_device_payment_method_music_churn_rate'] = df.groupby(['Location', 'Device Class', 'Payment Method', 'Music Product'])['Churn Label'].transform('mean')
df['location_device_payment_method_education_churn_rate'] = df.groupby(['Location', 'Device Class', 'Payment Method', 'Education Product'])['Churn Label'].transform('mean')
df['location_device_payment_method_call_center_churn_rate'] = df.groupby(['Location', 'Device Class', 'Payment Method', 'Call Center'])['Churn Label'].transform('mean')
df['location_device_payment_method_video_churn_rate'] = df.groupby(['Location', 'Device Class', 'Payment Method', 'Video Product'])['Churn Label'].transform('mean')
df['location_device_payment_method_myapp_churn_rate'] = df.groupby(['Location', 'Device Class', 'Payment Method', 'Use MyApp'])['Churn Label'].transform('mean')

df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate,device_games_churn_rate,device_music_churn_rate,device_education_churn_rate,device_call_center_churn_rate,device_video_churn_rate,device_myapp_churn_rate,device_service_churn_rate,device_location_churn_rate,device_payment_method_churn_rate,location_device_payment_method_churn_rate,location_device_payment_method_service_churn_rate,location_device_payment_method_games_churn_rate,location_device_payment_method_music_churn_rate,location_device_payment_method_education_churn_rate,location_device_payment_method_call_center_churn_rate,location_device_payment_method_video_churn_rate,location_device_payment_method_myapp_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180,0.094915,0.106814,0.252212,0.277554,0.226776,0.223611,0.202643,0.187318,0.207178,0.207675,0.223404,0.098039,0.149701,0.251701,0.279167,0.219585,0.238532
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060,0.493576,0.507701,0.499712,0.493722,0.453195,0.457993,0.604010,0.410626,0.532288,0.529884,0.660920,0.581976,0.590529,0.588811,0.583058,0.555556,0.585317
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703,0.493576,0.507701,0.315402,0.493722,0.392571,0.388921,0.379471,0.410626,0.532288,0.529884,0.466135,0.581976,0.590529,0.426108,0.583058,0.510236,0.484603
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005,0.493576,0.507701,0.315402,0.226328,0.392571,0.388921,0.318458,0.410626,0.532288,0.529884,0.390071,0.581976,0.590529,0.426108,0.301887,0.510236,0.484603
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005,0.493576,0.303053,0.315402,0.493722,0.392571,0.388921,0.318458,0.410626,0.289474,0.268657,0.235294,0.334426,0.194444,0.226054,0.345890,0.253521,0.251701

In [89]:
df.groupby(['Location', 'Device Class', 'Payment Method', 'Monthly Purchase (Thou. IDR)'])['Churn Label'].mean()

df['location_device_payment_method_monthly_purchase_churn_rate'] = df.groupby(['Location', 'Device Class', 'Payment Method', 'Monthly Purchase (Thou. IDR)'])['Churn Label'].transform('mean')
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate,device_games_churn_rate,device_music_churn_rate,device_education_churn_rate,device_call_center_churn_rate,device_video_churn_rate,device_myapp_churn_rate,device_service_churn_rate,device_location_churn_rate,device_payment_method_churn_rate,location_device_payment_method_churn_rate,location_device_payment_method_service_churn_rate,location_device_payment_method_games_churn_rate,location_device_payment_method_music_churn_rate,location_device_payment_method_education_churn_rate,location_device_payment_method_call_center_churn_rate,location_device_payment_method_video_churn_rate,location_device_payment_method_myapp_churn_rate,location_device_payment_method_monthly_purchase_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180,0.094915,0.106814,0.252212,0.277554,0.226776,0.223611,0.202643,0.187318,0.207178,0.207675,0.223404,0.098039,0.149701,0.251701,0.279167,0.219585,0.238532,1.000000
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060,0.493576,0.507701,0.499712,0.493722,0.453195,0.457993,0.604010,0.410626,0.532288,0.529884,0.660920,0.581976,0.590529,0.588811,0.583058,0.555556,0.585317,1.000000
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703,0.493576,0.507701,0.315402,0.493722,0.392571,0.388921,0.379471,0.410626,0.532288,0.529884,0.466135,0.581976,0.590529,0.426108,0.583058,0.510236,0.484603,0.333333
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005,0.493576,0.507701,0.315402,0.226328,0.392571,0.388921,0.318458,0.410626,0.532288,0.529884,0.390071,0.581976,0.590529,0.426108,0.301887,0.510236,0.484603,0.500000
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005,0.493576,0.303053,0.315402,0.493722,0.392571,0.388921,0.318458,0.410626,0.289474,0.268657,0.235294,0.334426,0.194444,0.226054,0.345890,0.253521,0.251701,0.500000

In [90]:
df['location_device_payment_method_monthly_purchase_games_churn_rate'] = df.groupby(['Location', 'Device Class', 'Payment Method', 'Monthly Purchase (Thou. IDR)', 'Games Product'])['Churn Label'].transform('mean')
df['location_device_payment_method_monthly_purchase_music_churn_rate'] = df.groupby(['Location', 'Device Class', 'Payment Method', 'Monthly Purchase (Thou. IDR)', 'Music Product'])['Churn Label'].transform('mean')
df['location_device_payment_method_monthly_purchase_education_churn_rate'] = df.groupby(['Location', 'Device Class', 'Payment Method', 'Monthly Purchase (Thou. IDR)', 'Education Product'])['Churn Label'].transform('mean')
df['location_device_payment_method_monthly_purchase_call_center_churn_rate'] = df.groupby(['Location', 'Device Class', 'Payment Method', 'Monthly Purchase (Thou. IDR)', 'Call Center'])['Churn Label'].transform('mean')
df['location_device_payment_method_monthly_purchase_video_churn_rate'] = df.groupby(['Location', 'Device Class', 'Payment Method', 'Monthly Purchase (Thou. IDR)', 'Video Product'])['Churn Label'].transform('mean')
df['location_device_payment_method_monthly_purchase_myapp_churn_rate'] = df.groupby(['Location', 'Device Class', 'Payment Method', 'Monthly Purchase (Thou. IDR)', 'Use MyApp'])['Churn Label'].transform('mean')

df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate,device_games_churn_rate,device_music_churn_rate,device_education_churn_rate,device_call_center_churn_rate,device_video_churn_rate,device_myapp_churn_rate,device_service_churn_rate,device_location_churn_rate,device_payment_method_churn_rate,location_device_payment_method_churn_rate,location_device_payment_method_service_churn_rate,location_device_payment_method_games_churn_rate,location_device_payment_method_music_churn_rate,location_device_payment_method_education_churn_rate,location_device_payment_method_call_center_churn_rate,location_device_payment_method_video_churn_rate,location_device_payment_method_myapp_churn_rate,location_device_payment_method_monthly_purchase_churn_rate,location_device_payment_method_monthly_purchase_games_churn_rate,location_device_payment_method_monthly_purchase_music_churn_rate,location_device_payment_method_monthly_purchase_education_churn_rate,location_device_payment_method_monthly_purchase_call_center_churn_rate,location_device_payment_method_monthly_purchase_video_churn_rate,location_device_payment_method_monthly_purchase_myapp_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180,0.094915,0.106814,0.252212,0.277554,0.226776,0.223611,0.202643,0.187318,0.207178,0.207675,0.223404,0.098039,0.149701,0.251701,0.279167,0.219585,0.238532,1.000000,1.0,1.0,1.0,1.000000,1.000000,1.000000
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060,0.493576,0.507701,0.499712,0.493722,0.453195,0.457993,0.604010,0.410626,0.532288,0.529884,0.660920,0.581976,0.590529,0.588811,0.583058,0.555556,0.585317,1.000000,1.0,1.0,1.0,1.000000,1.000000,1.000000
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703,0.493576,0.507701,0.315402,0.493722,0.392571,0.388921,0.379471,0.410626,0.532288,0.529884,0.466135,0.581976,0.590529,0.426108,0.583058,0.510236,0.484603,0.333333,0.5,0.5,0.5,0.333333,0.333333,0.333333
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005,0.493576,0.507701,0.315402,0.226328,0.392571,0.388921,0.318458,0.410626,0.532288,0.529884,0.390071,0.581976,0.590529,0.426108,0.301887,0.510236,0.484603,0.500000,0.5,1.0,0.5,1.000000,0.500000,0.500000
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005,0.493576,0.303053,0.315402,0.493722,0.392571,0.388921,0.318458,0.410626,0.289474,0.268657,0.235294,0.334426,0.194444,0.226054,0.345890,0.253521,0.251701,0.500000,0.5,0.5,0.5,1.000000,0.500000,0.500000

<h3>Binning</h3>

In [91]:
df['Tenure Months'].describe()

count    7043.000000
mean       32.371149
std        24.559481
min         0.000000
25%         9.000000
50%        29.000000
75%        55.000000
max        72.000000
Name: Tenure Months, dtype: float64

In [92]:
def categorize_tenure_percentile(tenure):
    if tenure <= df['Tenure Months'].quantile(0.25):
        return "Low Tenure"
    elif df['Tenure Months'].quantile(0.25) < tenure <= df['Tenure Months'].quantile(0.75):
        return "Medium Tenure"
    else:
        return "High Tenure"

df['Tenure_Category'] = df['Tenure Months'].apply(categorize_tenure_percentile)

In [93]:
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate,device_games_churn_rate,device_music_churn_rate,device_education_churn_rate,device_call_center_churn_rate,device_video_churn_rate,device_myapp_churn_rate,device_service_churn_rate,device_location_churn_rate,device_payment_method_churn_rate,location_device_payment_method_churn_rate,location_device_payment_method_service_churn_rate,location_device_payment_method_games_churn_rate,location_device_payment_method_music_churn_rate,location_device_payment_method_education_churn_rate,location_device_payment_method_call_center_churn_rate,location_device_payment_method_video_churn_rate,location_device_payment_method_myapp_churn_rate,location_device_payment_method_monthly_purchase_churn_rate,location_device_payment_method_monthly_purchase_games_churn_rate,location_device_payment_method_monthly_purchase_music_churn_rate,location_device_payment_method_monthly_purchase_education_churn_rate,location_device_payment_method_monthly_purchase_call_center_churn_rate,location_device_payment_method_monthly_purchase_video_churn_rate,location_device_payment_method_monthly_purchase_myapp_churn_rate,Tenure_Category
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180,0.094915,0.106814,0.252212,0.277554,0.226776,0.223611,0.202643,0.187318,0.207178,0.207675,0.223404,0.098039,0.149701,0.251701,0.279167,0.219585,0.238532,1.000000,1.0,1.0,1.0,1.000000,1.000000,1.000000,Low Tenure
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060,0.493576,0.507701,0.499712,0.493722,0.453195,0.457993,0.604010,0.410626,0.532288,0.529884,0.660920,0.581976,0.590529,0.588811,0.583058,0.555556,0.585317,1.000000,1.0,1.0,1.0,1.000000,1.000000,1.000000,Low Tenure
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703,0.493576,0.507701,0.315402,0.493722,0.392571,0.388921,0.379471,0.410626,0.532288,0.529884,0.466135,0.581976,0.590529,0.426108,0.583058,0.510236,0.484603,0.333333,0.5,0.5,0.5,0.333333,0.333333,0.333333,Low Tenure
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005,0.493576,0.507701,0.315402,0.226328,0.392571,0.388921,0.318458,0.410626,0.532288,0.529884,0.390071,0.581976,0.590529,0.426108,0.301887,0.510236,0.484603,0.500000,0.5,1.0,0.5,1.000000,0.500000,0.500000,Medium Tenure
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005,0.493576,0.303053,0.315402,0.493722,0.392571,0.388921,0.318458,0.410626,0.289474,0.268657,0.235294,0.334426,0.194444,0.226054,0.345890,0.253521,0.251701,0.500000,0.5,0.5,0.5,1.000000,0.500000,0.500000,Medium Tenure

In [94]:
df['CLTV (Predicted Thou. IDR)'].describe()

count    7043.000000
mean     5720.384481
std      1537.974298
min      2603.900000
25%      4509.700000
50%      5885.100000
75%      6994.650000
max      8450.000000
Name: CLTV (Predicted Thou. IDR), dtype: float64

In [95]:
def categorize_cltv_percentile(x):
    if x <= df['CLTV (Predicted Thou. IDR)'].quantile(0.25):
        return "Low CLTV"
    elif df['CLTV (Predicted Thou. IDR)'].quantile(0.25) < x <= df['CLTV (Predicted Thou. IDR)'].quantile(0.75):
        return "Medium CLTV"
    else:
        return "High CLTV"
    
df['CLTV_Category'] = df['CLTV (Predicted Thou. IDR)'].apply(categorize_cltv_percentile)
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate,device_games_churn_rate,device_music_churn_rate,device_education_churn_rate,device_call_center_churn_rate,device_video_churn_rate,device_myapp_churn_rate,device_service_churn_rate,device_location_churn_rate,device_payment_method_churn_rate,location_device_payment_method_churn_rate,location_device_payment_method_service_churn_rate,location_device_payment_method_games_churn_rate,location_device_payment_method_music_churn_rate,location_device_payment_method_education_churn_rate,location_device_payment_method_call_center_churn_rate,location_device_payment_method_video_churn_rate,location_device_payment_method_myapp_churn_rate,location_device_payment_method_monthly_purchase_churn_rate,location_device_payment_method_monthly_purchase_games_churn_rate,location_device_payment_method_monthly_purchase_music_churn_rate,location_device_payment_method_monthly_purchase_education_churn_rate,location_device_payment_method_monthly_purchase_call_center_churn_rate,location_device_payment_method_monthly_purchase_video_churn_rate,location_device_payment_method_monthly_purchase_myapp_churn_rate,Tenure_Category,CLTV_Category
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180,0.094915,0.106814,0.252212,0.277554,0.226776,0.223611,0.202643,0.187318,0.207178,0.207675,0.223404,0.098039,0.149701,0.251701,0.279167,0.219585,0.238532,1.000000,1.0,1.0,1.0,1.000000,1.000000,1.000000,Low Tenure,Low CLTV
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060,0.493576,0.507701,0.499712,0.493722,0.453195,0.457993,0.604010,0.410626,0.532288,0.529884,0.660920,0.581976,0.590529,0.588811,0.583058,0.555556,0.585317,1.000000,1.0,1.0,1.0,1.000000,1.000000,1.000000,Low Tenure,Low CLTV
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703,0.493576,0.507701,0.315402,0.493722,0.392571,0.388921,0.379471,0.410626,0.532288,0.529884,0.466135,0.581976,0.590529,0.426108,0.583058,0.510236,0.484603,0.333333,0.5,0.5,0.5,0.333333,0.333333,0.333333,Low Tenure,Medium CLTV
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005,0.493576,0.507701,0.315402,0.226328,0.392571,0.388921,0.318458,0.410626,0.532288,0.529884,0.390071,0.581976,0.590529,0.426108,0.301887,0.510236,0.484603,0.500000,0.5,1.0,0.5,1.000000,0.500000,0.500000,Medium Tenure,Medium CLTV
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005,0.493576,0.303053,0.315402,0.493722,0.392571,0.388921,0.318458,0.410626,0.289474,0.268657,0.235294,0.334426,0.194444,0.226054,0.345890,0.253521,0.251701,0.500000,0.5,0.5,0.5,1.000000,0.500000,0.500000,Medium Tenure,Medium CLTV

In [96]:
df['Monthly Purchase (Thou. IDR)'].describe()

count    7043.000000
mean       84.190200
std        39.117061
min        23.725000
25%        46.150000
50%        91.455000
75%       116.805000
max       154.375000
Name: Monthly Purchase (Thou. IDR), dtype: float64

In [97]:
def categorize_monthlyPurchase_percentile(x):
    if x <= df['Monthly Purchase (Thou. IDR)'].quantile(0.25):
        return "Low Monthly Purchase"
    elif df['Monthly Purchase (Thou. IDR)'].quantile(0.25) < x <= df['Monthly Purchase (Thou. IDR)'].quantile(0.75):
        return "Medium Monthly Purchase"
    else:
        return "High Monthly Purchase"
    
df['MonthlyPurchase_Category'] = df['Monthly Purchase (Thou. IDR)'].apply(categorize_monthlyPurchase_percentile)
df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate,device_games_churn_rate,device_music_churn_rate,device_education_churn_rate,device_call_center_churn_rate,device_video_churn_rate,device_myapp_churn_rate,device_service_churn_rate,device_location_churn_rate,device_payment_method_churn_rate,location_device_payment_method_churn_rate,location_device_payment_method_service_churn_rate,location_device_payment_method_games_churn_rate,location_device_payment_method_music_churn_rate,location_device_payment_method_education_churn_rate,location_device_payment_method_call_center_churn_rate,location_device_payment_method_video_churn_rate,location_device_payment_method_myapp_churn_rate,location_device_payment_method_monthly_purchase_churn_rate,location_device_payment_method_monthly_purchase_games_churn_rate,location_device_payment_method_monthly_purchase_music_churn_rate,location_device_payment_method_monthly_purchase_education_churn_rate,location_device_payment_method_monthly_purchase_call_center_churn_rate,location_device_payment_method_monthly_purchase_video_churn_rate,location_device_payment_method_monthly_purchase_myapp_churn_rate,Tenure_Category,CLTV_Category,MonthlyPurchase_Category
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180,0.094915,0.106814,0.252212,0.277554,0.226776,0.223611,0.202643,0.187318,0.207178,0.207675,0.223404,0.098039,0.149701,0.251701,0.279167,0.219585,0.238532,1.000000,1.0,1.0,1.0,1.000000,1.000000,1.000000,Low Tenure,Low CLTV,Medium Monthly Purchase
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060,0.493576,0.507701,0.499712,0.493722,0.453195,0.457993,0.604010,0.410626,0.532288,0.529884,0.660920,0.581976,0.590529,0.588811,0.583058,0.555556,0.585317,1.000000,1.0,1.0,1.0,1.000000,1.000000,1.000000,Low Tenure,Low CLTV,Medium Monthly Purchase
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703,0.493576,0.507701,0.315402,0.493722,0.392571,0.388921,0.379471,0.410626,0.532288,0.529884,0.466135,0.581976,0.590529,0.426108,0.583058,0.510236,0.484603,0.333333,0.5,0.5,0.5,0.333333,0.333333,0.333333,Low Tenure,Medium CLTV,High Monthly Purchase
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005,0.493576,0.507701,0.315402,0.226328,0.392571,0.388921,0.318458,0.410626,0.532288,0.529884,0.390071,0.581976,0.590529,0.426108,0.301887,0.510236,0.484603,0.500000,0.5,1.0,0.5,1.000000,0.500000,0.500000,Medium Tenure,Medium CLTV,High Monthly Purchase
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005,0.493576,0.303053,0.315402,0.493722,0.392571,0.388921,0.318458,0.410626,0.289474,0.268657,0.235294,0.334426,0.194444,0.226054,0.345890,0.253521,0.251701,0.500000,0.5,0.5,0.5,1.000000,0.500000,0.500000,Medium Tenure,Medium CLTV,High Monthly Purchase

In [107]:
df['tenure_cltv_category'] = df['Tenure_Category'] + " " + df['CLTV_Category']
df['tenure_monthly_purchase_category'] = df['Tenure_Category'] + " " + df['MonthlyPurchase_Category']
df['cltv_monthly_purchase_category'] = df['CLTV_Category'] + " " + df['MonthlyPurchase_Category']
df['tenure_cltv_monthly_purchase_category'] = df['Tenure_Category'] + " " + df['CLTV_Category'] + " " + df['MonthlyPurchase_Category']

df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate,device_games_churn_rate,device_music_churn_rate,device_education_churn_rate,device_call_center_churn_rate,device_video_churn_rate,device_myapp_churn_rate,device_service_churn_rate,device_location_churn_rate,device_payment_method_churn_rate,location_device_payment_method_churn_rate,location_device_payment_method_service_churn_rate,location_device_payment_method_games_churn_rate,location_device_payment_method_music_churn_rate,location_device_payment_method_education_churn_rate,location_device_payment_method_call_center_churn_rate,location_device_payment_method_video_churn_rate,location_device_payment_method_myapp_churn_rate,location_device_payment_method_monthly_purchase_churn_rate,location_device_payment_method_monthly_purchase_games_churn_rate,location_device_payment_method_monthly_purchase_music_churn_rate,location_device_payment_method_monthly_purchase_education_churn_rate,location_device_payment_method_monthly_purchase_call_center_churn_rate,location_device_payment_method_monthly_purchase_video_churn_rate,location_device_payment_method_monthly_purchase_myapp_churn_rate,Tenure_Category,CLTV_Category,MonthlyPurchase_Category,tenure_cltv_category,tenure_cltv_churn_rate,tenure_monthly_purchase_category,cltv_monthly_purchase_category,tenure_cltv_monthly_purchase_category
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180,0.094915,0.106814,0.252212,0.277554,0.226776,0.223611,0.202643,0.187318,0.207178,0.207675,0.223404,0.098039,0.149701,0.251701,0.279167,0.219585,0.238532,1.000000,1.0,1.0,1.0,1.000000,1.000000,1.000000,Low Tenure,Low CLTV,Medium Monthly Purchase,Low Tenure Low CLTV,0.487218,Low Tenure Medium Monthly Purchase,Low CLTV Medium Monthly Purchase,Low Tenure Low CLTV Medium Monthly Purchase
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060,0.493576,0.507701,0.499712,0.493722,0.453195,0.457993,0.604010,0.410626,0.532288,0.529884,0.660920,0.581976,0.590529,0.588811,0.583058,0.555556,0.585317,1.000000,1.0,1.0,1.0,1.000000,1.000000,1.000000,Low Tenure,Low CLTV,Medium Monthly Purchase,Low Tenure Low CLTV,0.487218,Low Tenure Medium Monthly Purchase,Low CLTV Medium Monthly Purchase,Low Tenure Low CLTV Medium Monthly Purchase
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703,0.493576,0.507701,0.315402,0.493722,0.392571,0.388921,0.379471,0.410626,0.532288,0.529884,0.466135,0.581976,0.590529,0.426108,0.583058,0.510236,0.484603,0.333333,0.5,0.5,0.5,0.333333,0.333333,0.333333,Low Tenure,Medium CLTV,High Monthly Purchase,Low Tenure Medium CLTV,0.503417,Low Tenure High Monthly Purchase,Medium CLTV High Monthly Purchase,Low Tenure Medium CLTV High Monthly Purchase
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005,0.493576,0.507701,0.315402,0.226328,0.392571,0.388921,0.318458,0.410626,0.532288,0.529884,0.390071,0.581976,0.590529,0.426108,0.301887,0.510236,0.484603,0.500000,0.5,1.0,0.5,1.000000,0.500000,0.500000,Medium Tenure,Medium CLTV,High Monthly Purchase,Medium Tenure Medium CLTV,0.226968,Medium Tenure High Monthly Purchase,Medium CLTV High Monthly Purchase,Medium Tenure Medium CLTV High Monthly Purchase
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005,0.493576,0.303053,0.315402,0.493722,0.392571,0.388921,0.318458,0.410626,0.289474,0.268657,0.235294,0.334426,0.194444,0.226054,0.345890,0.253521,0.251701,0.500000,0.5,0.5,0.5,1.000000,0.500000,0.500000,Medium Tenure,Medium CLTV,High Monthly Purchase,Medium Tenure Medium CLTV,0.226968,Medium Tenure High Monthly Purchase,Medium CLTV High Monthly Purchase,Medium Tenure Medium CLTV High Monthly Purchase

In [108]:
df['tenure_cltv_churn_rate'] = df['tenure_cltv_category'].map(df.groupby('tenure_cltv_category')['Churn Label'].mean())
df['tenure_monthly_purchase_churn_rate'] = df['tenure_monthly_purchase_category'].map(df.groupby('tenure_monthly_purchase_category')['Churn Label'].mean())
df['cltv_monthly_purchase_churn_rate'] = df['cltv_monthly_purchase_category'].map(df.groupby('cltv_monthly_purchase_category')['Churn Label'].mean())
df['tenure_cltv_monthly_purchase_churn_rate'] = df['tenure_cltv_monthly_purchase_category'].map(df.groupby('tenure_cltv_monthly_purchase_category')['Churn Label'].mean())

df.head()

,Customer ID,Tenure Months,Location,Device Class,Games Product,Music Product,Education Product,Call Center,Video Product,Use MyApp,Payment Method,Monthly Purchase (Thou. IDR),Churn Label,Longitude,Latitude,CLTV (Predicted Thou. IDR),service_used,payment_method_churn_rate,location_churn_rate,device_churn_rate,games_churn_rate,music_churn_rate,education_churn_rate,call_center_churn_rate,video_churn_rate,myapp_churn_rate,service_used_churn_rate,device_games_churn_rate,device_music_churn_rate,device_education_churn_rate,device_call_center_churn_rate,device_video_churn_rate,device_myapp_churn_rate,device_service_churn_rate,device_location_churn_rate,device_payment_method_churn_rate,location_device_payment_method_churn_rate,location_device_payment_method_service_churn_rate,location_device_payment_method_games_churn_rate,location_device_payment_method_music_churn_rate,location_device_payment_method_education_churn_rate,location_device_payment_method_call_center_churn_rate,location_device_payment_method_video_churn_rate,location_device_payment_method_myapp_churn_rate,location_device_payment_method_monthly_purchase_churn_rate,location_device_payment_method_monthly_purchase_games_churn_rate,location_device_payment_method_monthly_purchase_music_churn_rate,location_device_payment_method_monthly_purchase_education_churn_rate,location_device_payment_method_monthly_purchase_call_center_churn_rate,location_device_payment_method_monthly_purchase_video_churn_rate,location_device_payment_method_monthly_purchase_myapp_churn_rate,Tenure_Category,CLTV_Category,MonthlyPurchase_Category,tenure_cltv_category,tenure_cltv_churn_rate,tenure_monthly_purchase_category,cltv_monthly_purchase_category,tenure_cltv_monthly_purchase_category,tenure_monthly_purchase_churn_rate,cltv_monthly_purchase_churn_rate,tenure_cltv_monthly_purchase_churn_rate
0,0,2,Jakarta,Mid End,1,1,0,0,0,0,Digital Wallet,70.005,1,106.816666,-6.2,4210.7,2,0.191067,0.26297,0.189591,0.146112,0.215315,0.286518,0.311862,0.243312,0.243795,0.358180,0.094915,0.106814,0.252212,0.277554,0.226776,0.223611,0.202643,0.187318,0.207178,0.207675,0.223404,0.098039,0.149701,0.251701,0.279167,0.219585,0.238532,1.000000,1.0,1.0,1.0,1.000000,1.000000,1.000000,Low Tenure,Low CLTV,Medium Monthly Purchase,Low Tenure Low CLTV,0.487218,Low Tenure Medium Monthly Purchase,Low CLTV Medium Monthly Purchase,Low Tenure Low CLTV Medium Monthly Purchase,0.570925,0.388945,0.553699
1,1,2,Jakarta,High End,0,0,0,0,0,0,Pulsa,91.910,1,106.816666,-6.2,3511.3,0,0.452854,0.26297,0.418928,0.313296,0.291721,0.286518,0.311862,0.243312,0.243795,0.214060,0.493576,0.507701,0.499712,0.493722,0.453195,0.457993,0.604010,0.410626,0.532288,0.529884,0.660920,0.581976,0.590529,0.588811,0.583058,0.555556,0.585317,1.000000,1.0,1.0,1.0,1.000000,1.000000,1.000000,Low Tenure,Low CLTV,Medium Monthly Purchase,Low Tenure Low CLTV,0.487218,Low Tenure Medium Monthly Purchase,Low CLTV Medium Monthly Purchase,Low Tenure Low CLTV Medium Monthly Purchase,0.570925,0.388945,0.553699
2,2,8,Jakarta,High End,0,0,1,0,1,1,Pulsa,129.545,1,106.816666,-6.2,6983.6,3,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.311862,0.300702,0.299414,0.273703,0.493576,0.507701,0.315402,0.493722,0.392571,0.388921,0.379471,0.410626,0.532288,0.529884,0.466135,0.581976,0.590529,0.426108,0.583058,0.510236,0.484603,0.333333,0.5,0.5,0.5,0.333333,0.333333,0.333333,Low Tenure,Medium CLTV,High Monthly Purchase,Low Tenure Medium CLTV,0.503417,Low Tenure High Monthly Purchase,Medium CLTV High Monthly Purchase,Low Tenure Medium CLTV High Monthly Purchase,0.747059,0.305344,0.691358
3,3,28,Jakarta,High End,0,0,1,1,1,1,Pulsa,136.240,1,106.816666,-6.2,6503.9,4,0.452854,0.26297,0.418928,0.313296,0.291721,0.225021,0.151663,0.300702,0.299414,0.223005,0.493576,0.507701,0.315402,0.226328,0.392571,0.388921,0.318458,0.410626,0.532288,0.529884,0.390071,0.581976,0.590529,0.426108,0.301887,0.510236,0.484603,0.500000,0.5,1.0,0.5,1.000000,0.500000,0.500000,Medium Tenure,Medium CLTV,High Monthly Purchase,Medium Tenure Medium CLTV,0.226968,Medium Tenure High Monthly Purchase,Medium CLTV High Monthly Purchase,Medium Tenure Medium CLTV High Monthly Purchase,0.404678,0.305344,0.380048
4,4,49,Jakarta,High End,0,1,1,0,1,1,Debit,134.810,1,106.816666,-6.2,6942.0,4,0.167098,0.26297,0.418928,0.313296,0.215315,0.225021,0.311862,0.300702,0.299414,0.223005,0.493576,0.303053,0.315402,0.493722,0.392571,0.388921,0.318458,0.410626,0.289474,0.268657,0.235294,0.334426,0.194444,0.226054,0.345890,0.253521,0.251701,0.500000,0.5,0.5,0.5,1.000000,0.500000,0.500000,Medium Tenure,Medium CLTV,High Monthly Purchase,Medium Tenure Medium CLTV,0.226968,Medium Tenure High Monthly Purchase,Medium CLTV High Monthly Purchase,Medium Tenure Medium CLTV High Monthly Purchase,0.404678,0.305344,0.380048

In [100]:
df.columns

Index(['Customer ID', 'Tenure Months', 'Location', 'Device Class',
       'Games Product', 'Music Product', 'Education Product', 'Call Center',
       'Video Product', 'Use MyApp', 'Payment Method',
       'Monthly Purchase (Thou. IDR)', 'Churn Label', 'Longitude', 'Latitude',
       'CLTV (Predicted Thou. IDR)', 'service_used',
       'payment_method_churn_rate', 'location_churn_rate', 'device_churn_rate',
       'games_churn_rate', 'music_churn_rate', 'education_churn_rate',
       'call_center_churn_rate', 'video_churn_rate', 'myapp_churn_rate',
       'service_used_churn_rate', 'device_games_churn_rate',
       'device_music_churn_rate', 'device_education_churn_rate',
       'device_call_center_churn_rate', 'device_video_churn_rate',
       'device_myapp_churn_rate', 'device_service_churn_rate',
       'device_location_churn_rate', 'device_payment_method_churn_rate',
       'location_device_payment_method_churn_rate',
       'location_device_payment_method_service_churn_rate',
       'location_device_payment_method_games_churn_rate',
       'location_device_payment_method_music_churn_rate',
       'location_device_payment_method_education_churn_rate',
       'location_device_payment_method_call_center_churn_rate',
       'location_device_payment_method_video_churn_rate',
       'location_device_payment_method_myapp_churn_rate',
       'location_device_payment_method_monthly_purchase_churn_rate',
       'location_device_payment_method_monthly_purchase_games_churn_rate',
       'location_device_payment_method_monthly_purchase_music_churn_rate',
       'location_device_payment_method_monthly_purchase_education_churn_rate',
       'location_device_payment_method_monthly_purchase_call_center_churn_rate',
       'location_device_payment_method_monthly_purchase_video_churn_rate',
       'location_device_payment_method_monthly_purchase_myapp_churn_rate',
       'Tenure_Category', 'CLTV_Category', 'MonthlyPurchase_Category'],
      dtype='object')

In [109]:
# save to new file
df.to_excel('data_modified_v3.xlsx', index=False)